server:
  port: 8081

spring:
  application:
    name: consumer-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: consumer-service

  protocol:
    port: 20881
    name: dubbo
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: org.example.service.serviceImpl


